### ISSUE TITLE
스터디 규칙 정하기

### ISSUE THREAD

**Issue by 70825** [woowacourse-study/2023-algorithm-study#1]
스터디를 진행하기 전에 각자가 원하는 방향성이나 규칙, 논의할 내용을 적어주세요

저는 아래에 예시로 적을게요

<br/>

### 논의할 내용
1. 스터디를 시작하기 전에 각자 알고리즘 실력이 다르기 때문에 시작 난이도를 어떻게 해야할지 이야기가 필요해요
    - ex) 워밍업으로 다양한 유형으로, 쉬운 문제부터 (아니면 이걸 방학중에..??)
    - ex) 바로 프로그래머스 Lv.1 ~ Lv.3, 백준 브론즈~골드 다양한 난이도의 문제 풀기

2. 문제 선정 방식
    - 문제 개수, 문제 선정 방법, ...
    - ex) 매주마다 한 명씩 한 문제를 정해오기, 4명이라면 4문제를 가져와 이번주 안에 4문제를 풀기 (각 문제는 서로 다른 유형이어야함)

3. 스터디 규칙
    - 매주마다 문제를 풀지 못했을 경우에 대한 벌칙
      - ex) 커피 한 잔씩 돌리기
    - PR은 언제까지 보내야할지, 문제 선정은 언제까지 해야할지
      - ex) 쉬는 날도 있어야하니까 PR은 토요일 자정까지, 문제 선정은 일요일 자정까지

<br/>
<br/>

### 질문
1. 코딩테스트에 자주 나오는 유형은 구현 문제인데, 매주마다 구현 문제는 1문제씩 고정적으로 푸는건 어떤가요?

2. 코딩테스트는 무엇보다 실전이 중요하다고 생각해요.
그래서 주마다 한 번씩 백준 - 그룹 - 연습 기능을 사용해서 시간 제한을 두고 문제 푸는 것도 추가하는건 어떤가요? (평일 저녁이나 주말)

**Comment by TaeyeonRoyce** [comment]
제가 생각하는 스터디 방식은 다음과 같습니다.

### 난이도 & 문제 선정 방식
말씀대로 각자의 알고리즘 실력이 다른걸 고려하여 문제 선정은 자유로 하면 좋을 것 같습니다!
각자 동일한 문제를 풀어오는 건 아래 질문 내용에 적어두신 [구현 유형] 문제를 공통으로 풀어서 공유하면 어떨까욥
=> [주간 공통 문제 1개] + [개별 선정 문제 1 + n 개]

### 스터디 규칙
커피 한 잔씩 돌리기 좋아요
PR은 주 단위로 보내고, [공통 문제 + 개인 선정 문제 최소 1개 이상]을 포함하면 어떨까요
PR은 주마다 [백준 - 그룹 - 연습] 하는 전날까지 올리는걸로...? + 오프라인으로 모각코해도 좋은데..ㅎ

**Comment by hyeonjerry** [comment]
## 난이도 및 문제 선정 방식

매 주마다 특정 문제 유형을 정하고 자신의 수준에 맞는 문제를 찾아 풀어오는건 어떤신가요?
예를 들어 이번 주에는 "정렬" 유형을 정하고 자신의 수준이 "실버"라면 실버 중 정렬에 해당하는 문제를 풀어오는 식입니다.
이렇게 하면 모두가 문제를 풀어왔을 때 해당 유형에 대한 소감과 팁(?)을 나눌 수 있고 특정 유형의 문제만 푸는 것도 막을 수 있다는 장점이 있다고 생각해요.

## 스터디 규칙

### 문제 개수
위에서 말씀하신 것처럼 구현 1문제와 해당 주간에 선정된 유형 1문제로 총 2문제 어떠신가요?

### 벌칙
- 2문제 모두 풀지 못했을 경우 커피
- 1문제만 풀지 못했을 경우 경고 (2개 누적시 커피)
**단, 노력한 흔적이 충분하다고 판단될 경우 구성원 전체의 동의하에 벌칙을 면제할 수 있다.**

**Comment by 70825** [comment]
@TaeyeonRoyce 
오프라인 저도 좋아요
생각해보니 처음엔 각자 문제 선정해서 풀다가 나중엔 똑같은 문제를 풀어도 될 것 같네요

@Hyeonjae-K 
아 제가 중의적으로 적은 것 같아요. 문제 개수는 구현 1문제 + 각자 가져온 문제 1개씩 해서 1+N개의 문제를 푸는 것이었어요. 내용 수정했습니다
그리고 주마다 한 개의 유형을 정하는건 레벨 3 동안 8개의 유형을 배운다는건데 너무 느리지 않을까여

**Comment by TaeyeonRoyce** [comment]
@Hyeonjae-K 의견도 좋아보이네요!
유형을 하나 정해서 해당하는 문제를 각자의 수준에 맞게 풀어오면 해당 알고리즘에 대한 개념 익히기도 좋고 다양한 문제를 발견할 수 있어보여요
유형 자체가 8개만 있으니 여러번 해도 되고, 8개 중에서 매주 랜덤으로 선정해도 좋아보입니당.

근데 오프라인 실전 연습은 너무 좋아보여요...ㅎ

**Comment by yenawee** [comment]
구현 한 문제 + 주차마다 유형하나씩 정해서 개인별 랜덤 문제 풀기 좋습니다!

스터디 목적을 코딩테스트 실전 준비로 방향을 딱 정하는게 어떨까요??

각자 문제 소개 및 풀이방식 공유는 주 1회 1시간으로 하면 좋을거같아요
PR 은 스터디 시작 전까지 날리기, 다음 문제 선정은 스터디날 다음날의 자정까지 공유 (금요일 스터디면 일요일 되는 자정) 이 어떨까요?? 

그리고 실전연습도 너무 좋다고 생각합니다
캠퍼스가 어떻게 배정될지 모르지만 줌이나 게더에 카메라 켜고 해도 실전과 동일한 상황 만들 수 있어서  좋을거같아요

근데 이렇게 되면 스터디 시간이 주 2회라 부담이
좀 커질수 있다는 생각이 들어서 서로 문제 풀어서 공유하는 것은 글로 남이 알아볼 수 있게 예쁘게 정리해서 PR 날리고 코멘트로 질답하고
실전 연습을 스터디 시간에 함께 하는것도 좋을거같아요!
글로 정리하는 것이 시간이 오래걸리긴 하지만 정리하면서 확실하게 문제에 대해 습득할 수 있는 장점이 있을거같습니다 ㅎㅎ

**Comment by 70825** [comment]
@yenawee 
코테 실전 준비 목적으로 하는거 좋아요

실전 연습은 각자 1~2문제씩 선정하는 것도 좋고, 아니면 생각보다 문제 선정하는데 오래 걸리는데, 작년에 동아리 스터디할 때 수십번 열었어서 제가 따로 관리할 수도 있어요

PR 날릴 때 풀이 보내주면 코드도 더 잘 이해할 수 있어서 좋은 것 같아요!
